server:
  port: ${SERVER_PORT:9050}
spring:
  application:
    name: tech_challenge_hospital
  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:challenge_hospital}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          isolation: 2
        cache:
          use_second_level_cache: false
          use_query_cache: false
        type:
          enumType:
            type: pgsql_enum
    open-in-view: false
    show-sql: true



