name: fiap_technical_challenge_adj

volumes:
  database_hospital:
    name: database_hospital

networks:
  communication: # conexão com infra-local e acesso a internet - tipo bridge
    name: communication
    driver: bridge

services:

  challenge_hospital:
    container_name: challenge_hospital
    image: juniorsmartins/challenge_hospital:v0.0.1
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        APP_NAME: "challenge_hospital"
        APP_VERSION: "v0.0.1"
        APP_DESCRIPTION: "Serviço de Crud de hospital."
    ports:
      - "9050:9050"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      - DB_HOST=challenge_database_hospital
      - DB_NAME=database_hospital
      - DB_PORT=5432
    restart: on-failure
    networks:
      - communication
    depends_on:
      challenge_database_hospital:
        condition: service_started

  challenge_database_hospital:
    container_name: challenge_database_hospital
    image: postgres:16.0
    ports:
      - "5501:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: on-failure
    environment:
      - POSTGRES_DB=database_hospital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_hospital:/var/lib/postgresql/data
    networks:
      - communication